Repository 2011-FSA-Alpha/GraceShopper, pull requests merged in 2021-01, with the labels that each got.

#37 Order confirmed
  client/components/OrderConfirmed.js
  client/components/OrderConfirmed.spec.js
Labels: enhancement

#40 Not found
  client/components/NotFound.js
  client/components/NotFound.spec.js
Labels: enhancement

#44 Seed orders
  script/seed.js
  server/db/models/OrderProducts.js
Labels: enhancement

#64 fix(build webpack -p and bundle.js into production)
  package.json
Labels: bug

#79 feat(home page image carousel scrolls through images)
  .gitignore
  client/components/Carousel.js
  client/components/Home.js
  client/components/index.js
  client/index.js
  fonts/slick.eot
  fonts/slick.svg
  fonts/slick.ttf
  fonts/slick.woff
  package-lock.json
  package.json
  public/index.html
  script/largeSeed.js
  webpack.config.js
Labels: enhancement

#86 refactor(give proper access to all routes to avoid malicious input or manipulation)
  .gitignore
  server/api/order.js
  server/api/products.js
  server/api/users.js
  server/util/adminOnly.js
  urls.txt
Labels: enhancement

#89 fix(tweak carousel)
  client/components/Carousel.js
  client/components/Home.js
Labels: enhancement

#91 feat(re-integrate local login feature)
  client/components/auth-form.js
  client/store/user.js
  server/db/models/user.js
Labels: enhancement

#88 Not found
  client/components/AddProductForm.js
  client/components/index.js
  client/routes.js
  client/store/singleProduct.js
  server/api/products.js
  server/auth/google.js
Labels: bug, invalid
